spring:
  cloud:
    gateway:
      routes:
      - id: ms-products
        uri: lb://ms-products
        predicates:
        - Path=/api/products/**
        filters:
        - StripPrefix=2
        - name: SampleCookie
          args:
            message: hola mi mensaje personalizado para productos!
            name: user
            value: axel
      - id: ms-items
        uri: lb://ms-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, aghsa7s65d67ad6s6s7d7
        - AddResponseHeader=tokeb-response, 9zx9z9xz9xz9x9z9x9zx
        - AddRequestParameter=name, axel