services:
  ms-config-server:
    container_name: ms-config-server
    image: ms-configserver:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - springcloud
  ms-eureka-server:
    container_name: ms-eureka-server
    image:  ms-eurekaserver:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  mysql8:
    container_name: mysql8 
    image: mysql:8.0
    ports:
      - "3307:3306"
    restart: always
    networks:
      - springcloud
    environment:
      - MYSQL_ROOT_PASSWORD=sasa
      - MYSQL_DATABASE=db_microservices_spring_cloud_2024
  ms-zipkin-server:
    container_name: ms-zipkin-server 
    image: ms-zipkinserver:latest
    ports:
      - "9411:9411"
    restart: always
    networks:
      - springcloud
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=sasa
      - MYSQL_HOST=mysql8
    depends_on:
      - mysql8
  ms-products-server:
    #container_name: ms-products-server
    image: ms-products:v1
    deploy: 
      replicas: 3
    restart: always
    networks:
      - springcloud
    depends_on:
      - ms-eureka-server
      - mysql8
      - ms-zipkin-server
  ms-items-server:
    container_name: ms-items-server 
    image: ms-items:v1
    ports:
      - "8005:8005"
      - "8002:8002"
      - "8007:8007"
    restart: always
    networks:
      - springcloud
    depends_on:
      - ms-eureka-server
      - ms-zipkin-server
      - ms-products-server
  ms-users-server:
    container_name: ms-users-server 
    image: ms-users:v1
    restart: always
    networks:
      - springcloud
    depends_on:
      - ms-eureka-server
      - ms-zipkin-server
      - mysql8
  ms-oauth2-server:
    container_name: ms-oauth2-server 
    image: ms-oauth2:v1
    restart: always
    ports:
      - "9100:9100"
    networks:
      - springcloud
    depends_on:
      - ms-eureka-server
      - ms-zipkin-server
      - ms-users-server
  ms-gateway-server:
    container_name: ms-gateway-server
    image: ms-gatewayserver:v1
    restart: always
    ports:
      - "8090:8090"
    networks:
      - springcloud
    environment:
      - IP_ADDR=http://192.168.1.184:9100
    depends_on:
      - ms-eureka-server
      - ms-zipkin-server
      - ms-products-server
      - ms-items-server 
      - ms-users-server
      - ms-oauth2-server 

networks:
  springcloud:    